package login.com.orangehemlive.demo.opensource;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

public class IRCTCSignup {
	public static void main(String arg[]) throws Exception
	{
		System.setProperty("webdriver.chrome.driver", "D:\\Workspace\\Jars and Drivers\\Drivers\\Chrome\\chromedriver.exe");
		WebDriver driver= new ChromeDriver();
		driver.get("https://www.irctc.co.in/eticketing/userSignUp.jsf");
		System.out.println("IRCTC Sign up page is opened");
		driver.manage().window().maximize();
		driver.findElement(By.name("userRegistrationForm:userName")).sendKeys("Testsai_907");
		System.out.println("User is entered");
		driver.findElement(By.linkText("Check Availability")).click();
		System.out.println("User id availability checked");
		driver.findElement(By.name("userRegistrationForm:password")).sendKeys("Testsai907");
		System.out.println("Password is entered");
		driver.findElement(By.name("userRegistrationForm:confpasword")).sendKeys("Testsai907");
		System.out.println("Password confirmation is done");
		WebElement securityquestion =driver.findElement(By.id("userRegistrationForm:securityQ"));
		Select s= new Select(securityquestion);
		s.selectByIndex(1);
		System.out.println("What was the name of your first school?");
		Thread.sleep(2000);
		driver.findElement(By.name("userRegistrationForm:securityAnswer")).sendKeys("Tapovan");
		System.out.println("Security answer is entered");
		WebElement pl=driver.findElement(By.name("userRegistrationForm:prelan"));
		Select s1= new Select(pl);
		s1.selectByVisibleText("English");
		System.out.println("Preferred language is selected");
		driver.findElement(By.name("userRegistrationForm:firstName")).sendKeys("Yellow");
		System.out.println("First name is entered");
		driver.findElement(By.name("userRegistrationForm:middleName")).sendKeys("Y");
		System.out.println("Middle name is entered");
		driver.findElement(By.name("userRegistrationForm:lastName")).sendKeys("Flower");
		System.out.println("Last name is entered");
		driver.findElement(By.xpath("//label[text()=' Female']")).click();
		System.out.println("gender  Female is selected");
		driver.findElement(By.xpath("//label[text()=' Married']")).click();
		System.out.println("Marital status is selected");
		WebElement birthday=driver.findElement(By.name("userRegistrationForm:dobDay"));
		Select s2= new Select(birthday);
		s2.selectByIndex(13);
		System.out.println("Birthday is selected");
		WebElement birthmonth=driver.findElement(By.name("userRegistrationForm:dobMonth"));
		Select s3= new Select(birthmonth);
		s3.selectByValue("03");
		//s3.deselectByValue("03");
		//Thread.sleep(2000);
		s3.selectByVisibleText("JUN");
		System.out.println("Birthmonth is selected");
		WebElement birthyear=driver.findElement(By.name("userRegistrationForm:dateOfBirth"));
		Select s4= new Select(birthyear);
		s4.selectByVisibleText("2000");
		System.out.println("Birthyear is selected");
		WebElement occupation=driver.findElement(By.name("userRegistrationForm:occupation"));
		Select s5= new Select(occupation);
		s5.selectByVisibleText("Private");
		driver.findElement(By.name("userRegistrationForm:uidno")).sendKeys("444455557777");
		System.out.println("Aadhar is entered");
		driver.findElement(By.name("userRegistrationForm:uidno")).sendKeys("444455557777");
		System.out.println("Aadhar is entered");
		driver.findElement(By.name("userRegistrationForm:idno")).sendKeys("4455557JA7");
		System.out.println("pan is entered");
		WebElement country=driver.findElement(By.name("userRegistrationForm:countries"));
		Select s6= new Select(country);
		s6.selectByVisibleText("India");
		System.out.println("country is selected");
		driver.findElement(By.name("userRegistrationForm:email")).sendKeys("a.vijetha@gmail.com");
		System.out.println("email is entered");
		driver.findElement(By.name("userRegistrationForm:mobile")).sendKeys("777888999");
		System.out.println("mobile is entered");
		WebElement nationality=driver.findElement(By.name("userRegistrationForm:nationalityId"));
		Select s7= new Select(nationality);
		s7.getOptions();
		s7.selectByVisibleText("India");
		System.out.println("Nationality is selected");
		driver.findElement(By.xpath("//input[@name='userRegistrationForm:address']")).sendKeys("309");
		System.out.println("door number is entered");
		driver.findElement(By.name("userRegistrationForm:street")).sendKeys("Green street");
		System.out.println("street is entered");
		driver.findElement(By.name("userRegistrationForm:area")).sendKeys("Miyapur");
		System.out.println("Area is entered");
		driver.findElement(By.name("userRegistrationForm:pincode")).sendKeys("500049");
		System.out.println("pincode is entered");
		//driver.findElement(By.name("userRegistrationForm:statesName")).sendKeys("Andhra Pradesh");
		//System.out.println("state is entered");
		WebElement city=driver.findElement(By.name("userRegistrationForm:cityName"));
		new Select(city);
		
		((JavascriptExecutor)driver).executeScript("window.scrollBy(0,250)", "");
		System.out.println("city is selected");
		WebElement pos=driver.findElement(By.name("userRegistrationForm:postofficeName"));
		new Select(pos);
		System.out.println("post ofice is selected");
		driver.findElement(By.name("userRegistrationForm:landline")).sendKeys("444508567");
		System.out.println("phone is entered");
		driver.findElement(By.xpath("//input[@id='userRegistrationForm:resAndOff:0']")).click();
		System.out.println("radio button is selected");
		driver.findElement(By.xpath("//input[@id='userRegistrationForm:newsletter:0']")).click();
		System.out.println("IRTC newsletter selected option NO");
		driver.findElement(By.id("userRegistrationForm:commercialpromo:1")).click();
		System.out.println("commercial promotion selected option NO");
		driver.findElement(By.id("userRegistrationForm:irctcsbicard")).click();
		System.out.println("inform card info through phone is opted as No");
		//driver.findElement(By.xpath("//a[text()='Submit Registration Form>>>']")).click();
	
	}
}
